services:
  redmine:
    image: redmine:alpine
    restart: unless-stopped
    volumes:
      - redmine-data:/usr/src/redmine/files
    healthcheck:
      test: wget -O /dev/null -q http://localhost:3000

  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      redmine:
        condition: service_healthy
    ports:
      - 443:443
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/redmine.conf
      - source: tls_crt
        target: /fullchain.pem
      - source: tls_crt_key
        target: /privkey.pem

configs:
  tls_crt:
    content: $TLS_CERT
  tls_crt_key:
    content: $TLS_CERT_KEY
  nginx_config:
    content: |
      server {
        listen  443 ssl;

        server_name ${SERVER_NAME};

        ssl_certificate /fullchain.pem;
        ssl_certificate_key /privkey.pem;

        location / {
          proxy_pass  http://redmine:3000;

          proxy_set_header Host $$http_host;
          proxy_set_header X-Real-IP $$remote_addr;
          proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $$scheme;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $$http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }

volumes:
  redmine-data:
